# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-schematized-config',
                'doc_host': 'https://aistriketeam.github.io',
                'git_url': 'https://github.com/aistriketeam/python-schematized-config',
                'lib_path': 'python_schematized_config'},
  'syms': { 'python_schematized_config.core': { 'python_schematized_config.core.foo': ( 'core.html#foo',
                                                                                        'python_schematized_config/core.py')}}}
