# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../nbs/01_cli.ipynb 2
from .core import ConfigValidator, load_json, extract_declared_items

import os
import sys
import argparse
import dotenv
from typing import Union
from fastcore.script import *

# %% ../nbs/01_cli.ipynb 6
@call_parse
def main(
    generate: str = None,              # path to a json schema that validates a dotenv
    schema: str = None,                 # path to json schema used for validation
    validate: Union[bool, str] = None,  # validate a dotenv; if a path not given, assume .env; requires <schema>
):
    "friendly tools to work with schemas and dotenv"
    
    if generate:
        sys.stdout.write(generate_sample_dotenv(generate))
    elif schema and validate:
        if validate is True:
            dotenv_path = '.env'
        else:
            dotenv_path = None
        validate_env(schema, dotenv_path)
